In [0]:
# 기본정보

students_score = [
                  {'num' : '1', 'name' : '김철수', 'kor' : 90, 'eng' : 80, 'math' : 85},
                  {'num' : '2', 'name' : '박제동', 'kor' : 85, 'eng' : 90, 'math' : 75},
                  {'num' : '3', 'name' : '홍길동', 'kor' : 95, 'eng' : 85, 'math' : 90},

]

In [0]:
# 추가
students_score.append({'num' : '4', 'name' : '김경섭', 'kor' : 88, 'eng' : 85, 'math' : 90})
students_score.append({'num' : '5', 'name' : '손진수', 'kor' : 96, 'eng' : 85, 'math' : 86})

In [58]:
students_score

[{'eng': 80, 'kor': 90, 'math': 85, 'name': '김철수', 'num': '1'},
 {'eng': 90, 'kor': 85, 'math': 75, 'name': '박제동', 'num': '2'},
 {'eng': 85, 'kor': 95, 'math': 90, 'name': '홍길동', 'num': '3'},
 {'eng': 85, 'kor': 88, 'math': 90, 'name': '김경섭', 'num': '4'},
 {'eng': 85, 'kor': 96, 'math': 86, 'name': '손진수', 'num': '5'}]

In [0]:
# 과목별로 점수 따로 저장 학급평균
kor = []
eng = []
math = []
class_avg = []

# 학생별 과목 더해서 총합, 평균 추가 
for num, student in enumerate(students_score):
  student['total'] = student['kor'] + student['eng'] + student['math']
  student['avg'] = round((student['kor'] + student['eng'] + student['math']) / 3)
  
  class_avg.insert(num, student['avg'])

  # 리스트에 과목별 점수 추가
  kor.insert(num,student['kor'])
  eng.insert(num, student['eng'])
  math.insert(num, student['math'])

In [60]:
# 과목별 평균 구함
kor_avg = sum(kor) / len(students_score)
eng_avg = sum(eng) / len(students_score)
math_avg = sum(math) / len(students_score)

# 학급평균 구함
class_avg_score = sum(class_avg) / len(students_score)

# 출력
print('class_avg : {}'.format(class_avg_score))
print('kor_avg : {0}\neng_avg : {1}\nmath_avg : {2}'.format(kor_avg, eng_avg, math_avg) )

class_avg : 87.0
kor_avg : 90.8,
eng_avg : 85.0
math_avg : 85.2

In [64]:
# 학생별 평균, 총점 출력
for i in students_score:
  print(i['name'] + '_avg ' + ":", i['avg'], 'total :', i['total'])

김철수_avg : 85 total : 255
박제동_avg : 83 total : 250
홍길동_avg : 90 total : 270
김경섭_avg : 88 total : 263
손진수_avg : 89 total : 267